return {
  ["workshop-1111658995"]={ configuration_options={  }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={
      ArrowsignEnable=true,
      CountdownEnable=false,
      HungerCost=0,
      Ownership=true,
      SanityCost=0 
    },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=true,
      Icebox=false,
      OnlyPlayer=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-1780476441"]={ configuration_options={  }, enabled=true },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=true,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=true,
      AutoStackManuallyDroppedItems=true,
      AutoStackPoop=true,
      AutoStackRange=10,
      AutoStackSeeds=true,
      AutoStackTwiggyTreeTwigs=false,
      ManualDropStackRange=5,
      ManualStackAsh=false,
      ManualStackMakeNewStackMainStack=false,
      ManualStackPoop=false,
      ManualStackSeeds=false,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=true 
    },
    enabled=true 
  },
  ["workshop-3235319974"]={
    configuration_options={
      key_v=118,
      key_x=120,
      key_z=122,
      set00=0,
      set1=true,
      set10=5,
      set11=true,
      set12=1,
      set13=false,
      set2=true,
      set3=true,
      set4=false,
      set5=true,
      set6=true,
      set7=true,
      wukongkey=114 
    },
    enabled=true 
  },
  ["workshop-3624411781"]={
    configuration_options={
      ["Bag Capacity"]=1200,
      ["Bag Spoilrate"]=0.75,
      Misc=0,
      ["Slurper Bag"]=0,
      SoulJar=false 
    },
    enabled=true 
  },
  ["workshop-374550642"]={
    configuration_options={
      FORCE_STACKSIZES=false,
      STACK_SIZE_LARGEITEM=99,
      STACK_SIZE_MEDITEM=99,
      STACK_SIZE_PELLET=120,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=99 
    },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-380423963"]={
    configuration_options={
      [""]=0,
      boulder_blue=1,
      boulder_purple=1,
      change_cave_loot=false,
      common_loot_charcoal=0.011,
      common_loot_flint=1,
      common_loot_rocks=1,
      cutlichen=0,
      durian=0,
      flintless_blue=1,
      flintless_purple=1,
      flintless_red=1,
      foliage=0,
      gears=0,
      goldvein_purple=1,
      goldvein_red=1,
      guano=0,
      ice=0,
      lightbulb=0,
      moon_green=1,
      moon_orange=1,
      moon_yellow=1,
      pinecone=0,
      rare_loot_bluegem=0.015,
      rare_loot_marble=0.015,
      rare_loot_redgem=0.015,
      rottenegg=0,
      seeds=0,
      spoiled_food=0,
      stalagmite_green=1,
      stalagmite_orange=1,
      stalagmite_yellow=1,
      uncommon_loot_goldnugget=0.05,
      uncommon_loot_mole=0.05,
      uncommon_loot_nitre=0.05,
      uncommon_loot_rabbit=0.05 
    },
    enabled=true 
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  } 
}