return {
  ["workshop-1111658995"]={ configuration_options={  }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={
      ArrowsignEnable=false,
      CountdownEnable=false,
      HungerCost=1,
      Ownership=true,
      SanityCost=1 
    },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      OnlyPlayer=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-1780476441"]={ configuration_options={  }, enabled=true },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=false,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=true,
      AutoStackManuallyDroppedItems=false,
      AutoStackPoop=false,
      AutoStackRange=10,
      AutoStackSeeds=false,
      AutoStackTwiggyTreeTwigs=false,
      ManualDropStackRange=5,
      ManualStackAsh=false,
      ManualStackMakeNewStackMainStack=false,
      ManualStackPoop=false,
      ManualStackSeeds=false,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=false 
    },
    enabled=true 
  },
  ["workshop-3235319974"]={
    configuration_options={
      key_v=118,
      key_x=120,
      key_z=122,
      set00=0,
      set1=true,
      set10=5,
      set11=true,
      set12=1,
      set13=false,
      set2=true,
      set3=true,
      set4=false,
      set5=true,
      set6=true,
      set7=true,
      wukongkey=114 
    },
    enabled=true 
  },
  ["workshop-3624411781"]={
    configuration_options={
      ["Bag Capacity"]=1200,
      ["Bag Spoilrate"]=0.75,
      Misc=0,
      ["Slurper Bag"]=0,
      SoulJar=false 
    },
    enabled=true 
  },
  ["workshop-374550642"]={
    configuration_options={
      FORCE_STACKSIZES=false,
      STACK_SIZE_LARGEITEM=99,
      STACK_SIZE_MEDITEM=99,
      STACK_SIZE_PELLET=120,
      STACK_SIZE_SMALLITEM=99,
      STACK_SIZE_TINYITEM=99 
    },
    enabled=true 
  },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true } 
}